// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkillSwap.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;

#nullable disable

namespace SkillSwap.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261002132849_AddRecognitionIncentives")]
    partial class AddRecognitionIncentives
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkillSwap.Platform.AssessmentPeerReview.Domain.Model.Aggregates.AssessmentAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BlueprintId")
                        .HasColumnType("integer")
                        .HasColumnName("blueprint_id");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean")
                        .HasColumnName("passed");

                    b.Property<string>("Score")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("score");

                    b.Property<string>("SelectedAnswers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("selected_answers");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasKey("Id");

                    b.HasIndex("BlueprintId")
                        .IsUnique()
                        .HasDatabaseName("ux_assessment_attempts_blueprint");

                    b.HasIndex("StudentId");

                    b.ToTable("assessment_attempts", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.AssessmentPeerReview.Domain.Model.Aggregates.VerificationCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<int>("AttemptId")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_id");

                    b.Property<string>("Decision")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("decision");

                    b.Property<string>("EvidenceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("evidence_url");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<int>("PathNodeId")
                        .HasColumnType("integer")
                        .HasColumnName("path_node_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("RubricNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("rubric_notes");

                    b.Property<string>("SkillTag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("skill_tag");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<int?>("VerifierUserId")
                        .HasColumnType("integer")
                        .HasColumnName("verifier_user_id");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId")
                        .IsUnique()
                        .HasDatabaseName("ux_verification_cases_attempt");

                    b.HasIndex("VerifierUserId");

                    b.HasIndex("SkillTag", "Status");

                    b.HasIndex("StudentId", "PathNodeId")
                        .IsUnique()
                        .HasDatabaseName("ux_verification_cases_one_open_per_student_node")
                        .HasFilter("status <> 'Resolved'");

                    b.ToTable("verification_cases", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.AssessmentPeerReview.Domain.Model.Aggregates.VerifierProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Available")
                        .HasColumnType("boolean")
                        .HasColumnName("available");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer")
                        .HasColumnName("review_count");

                    b.Property<string>("SkillTags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("skill_tags");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.Property<int>("VerifierUserId")
                        .HasColumnType("integer")
                        .HasColumnName("verifier_user_id");

                    b.HasKey("Id");

                    b.HasIndex("VerifierUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_verifier_profiles_user");

                    b.ToTable("verifier_profiles", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.CredentialVerification.Domain.Model.Aggregates.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificateNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("certificate_number");

                    b.Property<string>("CourseName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("course_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationHours")
                        .HasColumnType("integer")
                        .HasColumnName("duration_hours");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("file_hash");

                    b.Property<string>("HolderName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("holder_name");

                    b.Property<string>("InstitutionName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("institution_name");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<string>("OcrText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ocr_text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("QrPayload")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("qr_payload");

                    b.Property<int?>("RiskAssessment")
                        .HasColumnType("integer")
                        .HasColumnName("risk_score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StorageReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_reference");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("verification_code");

                    b.Property<string>("VerificationMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("verification_method");

                    b.Property<string>("VerificationUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("verification_url");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id");

                    b.HasIndex("CertificateNumber");

                    b.HasIndex("FileHash");

                    b.HasIndex("VerificationCode");

                    b.HasIndex("OwnerId", "FileHash")
                        .IsUnique();

                    b.ToTable("certificates", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("bio");

                    b.Property<string>("DeviceToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("device_token");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.LearningPathEngine.Domain.Model.Aggregates.AssessmentBlueprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<int>("PathNodeId")
                        .HasColumnType("integer")
                        .HasColumnName("path_node_id");

                    b.Property<string>("Questions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("questions");

                    b.Property<string>("SkillTag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("skill_tag");

                    b.HasKey("Id");

                    b.HasIndex("PathNodeId");

                    b.ToTable("assessment_blueprints", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.LearningPathEngine.Domain.Model.Aggregates.LearningPath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CareerGoal")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("career_goal");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasDatabaseName("ux_learning_paths_one_active_per_student")
                        .HasFilter("status = 'Active'");

                    b.ToTable("learning_paths", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.LearningPathEngine.Domain.Model.Entities.PathNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssessmentBlueprintId")
                        .HasColumnType("integer")
                        .HasColumnName("assessment_blueprint_id");

                    b.Property<int>("LearningPathId")
                        .HasColumnType("integer")
                        .HasColumnName("learning_path_id");

                    b.Property<int?>("LinkedCertificateId")
                        .HasColumnType("integer")
                        .HasColumnName("linked_certificate_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("node_order");

                    b.Property<string>("PrerequisiteSkillTags")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("prerequisites");

                    b.Property<string>("SkillTag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("skill_tag");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("LearningPathId", "Order")
                        .IsUnique();

                    b.HasIndex("LearningPathId", "SkillTag")
                        .IsUnique();

                    b.ToTable("path_nodes", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.RecognitionIncentives.Domain.Model.Aggregates.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Balance")
                        .HasColumnType("integer")
                        .HasColumnName("balance");

                    b.Property<int>("WalletOwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("wallet_owner_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("WalletOwnerId")
                        .IsUnique()
                        .HasDatabaseName("ux_wallets_owner");

                    b.ToTable("wallets", null, t =>
                        {
                            t.HasCheckConstraint("ck_wallets_balance_non_negative", "balance >= 0");
                        });
                });

            modelBuilder.Entity("SkillSwap.Platform.RecognitionIncentives.Domain.Model.Entities.CreditTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<int?>("RelatedCaseId")
                        .HasColumnType("integer")
                        .HasColumnName("related_case_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<int>("WalletId")
                        .HasColumnType("integer")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.HasIndex("WalletId", "RelatedCaseId")
                        .IsUnique()
                        .HasDatabaseName("ux_credit_transactions_wallet_case")
                        .HasFilter("related_case_id IS NOT NULL");

                    b.ToTable("credit_transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_credit_transactions_amount_positive", "amount > 0");
                        });
                });

            modelBuilder.Entity("SkillSwap.Platform.Reputation.Domain.Model.Aggregates.StudentEmployabilityScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VerifiedSkillsCount")
                        .HasColumnType("integer")
                        .HasColumnName("verified_skills_count");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasDatabaseName("ux_student_employability_scores_student");

                    b.ToTable("student_employability_scores", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.Reputation.Domain.Model.Aggregates.VerifierReliability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OverturnedDecisionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("overturned_decisions_count");

                    b.Property<int>("ResolvedCasesCount")
                        .HasColumnType("integer")
                        .HasColumnName("resolved_cases_count");

                    b.Property<int>("SanctionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("sanctions_count");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VerifierUserId")
                        .HasColumnType("integer")
                        .HasColumnName("verifier_user_id");

                    b.HasKey("Id");

                    b.HasIndex("VerifierUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_verifier_reliabilities_user");

                    b.ToTable("verifier_reliabilities", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.LearningPathEngine.Domain.Model.Entities.PathNode", b =>
                {
                    b.HasOne("SkillSwap.Platform.LearningPathEngine.Domain.Model.Aggregates.LearningPath", null)
                        .WithMany("Nodes")
                        .HasForeignKey("LearningPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillSwap.Platform.RecognitionIncentives.Domain.Model.Entities.CreditTransaction", b =>
                {
                    b.HasOne("SkillSwap.Platform.RecognitionIncentives.Domain.Model.Aggregates.Wallet", null)
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillSwap.Platform.LearningPathEngine.Domain.Model.Aggregates.LearningPath", b =>
                {
                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
