// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace SkillSwap.Platform.Tests.AssessmentPeerReview.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ReviewTheVerificationCasesFeature : object, global::Xunit.IClassFixture<ReviewTheVerificationCasesFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "AssessmentPeerReview/Features", "Review the verification cases", "  As a verifier\r\n  I want to review the cases assigned to me following the rubric" +
                "\r\n  So that the students get a fair decision from a peer", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CaseReview.feature"
#line hidden
        
        public ReviewTheVerificationCasesFeature(ReviewTheVerificationCasesFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("a signed-in student \"ana\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.AndAsync("a signed-in student \"bob\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 9
    await testRunner.AndAsync("a signed-in student \"carl\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
    await testRunner.AndAsync("\"ana\" has declared the goal \"quiero aprender a construir APIs REST con autenticac" +
                    "ión JWT\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
    await testRunner.AndAsync("\"bob\" has declared the goal \"quiero aprender a construir APIs REST con autenticac" +
                    "ión JWT\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
    await testRunner.AndAsync("\"bob\" has completed the skill \"networking-basics\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
    await testRunner.AndAsync("\"bob\" is a verifier of the skill \"networking-basics\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("AssessmentPeerReview/Features/CaseReview.feature.ndjson", 17);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A failed attempt is assigned to an available verifier")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Review the verification cases")]
        [global::Xunit.TraitAttribute("Description", "A failed attempt is assigned to an available verifier")]
        [global::Xunit.TraitAttribute("Category", "US24")]
        public async global::System.Threading.Tasks.Task AFailedAttemptIsAssignedToAnAvailableVerifier()
        {
            string[] tagsOfScenario = new string[] {
                    "US24"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A failed attempt is assigned to an available verifier", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 16
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 17
    await testRunner.GivenAsync("\"ana\" has failed the assessment of the skill \"networking-basics\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
    await testRunner.WhenAsync("\"bob\" consults the cases assigned to them", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
    await testRunner.ThenAsync("the response status is 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 20
    await testRunner.AndAsync("the number of assigned cases is 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
    await testRunner.AndAsync("the case of \"ana\" is \"Assigned\" to \"bob\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="The case waits when no verifier is available")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Review the verification cases")]
        [global::Xunit.TraitAttribute("Description", "The case waits when no verifier is available")]
        [global::Xunit.TraitAttribute("Category", "US24")]
        public async global::System.Threading.Tasks.Task TheCaseWaitsWhenNoVerifierIsAvailable()
        {
            string[] tagsOfScenario = new string[] {
                    "US24"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The case waits when no verifier is available", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 24
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 25
    await testRunner.GivenAsync("\"bob\" switches their availability off", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 26
    await testRunner.WhenAsync("\"ana\" has failed the assessment of the skill \"networking-basics\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 27
    await testRunner.ThenAsync("the case of \"ana\" is \"Pending\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A pending case is assigned when the verifier becomes available")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Review the verification cases")]
        [global::Xunit.TraitAttribute("Description", "A pending case is assigned when the verifier becomes available")]
        [global::Xunit.TraitAttribute("Category", "US24")]
        public async global::System.Threading.Tasks.Task APendingCaseIsAssignedWhenTheVerifierBecomesAvailable()
        {
            string[] tagsOfScenario = new string[] {
                    "US24"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A pending case is assigned when the verifier becomes available", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 30
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 31
    await testRunner.GivenAsync("\"bob\" switches their availability off", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 32
    await testRunner.AndAsync("\"ana\" has failed the assessment of the skill \"networking-basics\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
    await testRunner.WhenAsync("\"bob\" switches their availability on", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 34
    await testRunner.ThenAsync("the case of \"ana\" is \"Assigned\" to \"bob\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="The verifier sees the failed questions without the correct answers")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Review the verification cases")]
        [global::Xunit.TraitAttribute("Description", "The verifier sees the failed questions without the correct answers")]
        [global::Xunit.TraitAttribute("Category", "US25")]
        public async global::System.Threading.Tasks.Task TheVerifierSeesTheFailedQuestionsWithoutTheCorrectAnswers()
        {
            string[] tagsOfScenario = new string[] {
                    "US25"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The verifier sees the failed questions without the correct answers", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 37
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 38
    await testRunner.GivenAsync("\"ana\" has failed the assessment of the skill \"networking-basics\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 39
    await testRunner.WhenAsync("\"bob\" consults the case of \"ana\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 40
    await testRunner.ThenAsync("the response status is 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 41
    await testRunner.AndAsync("the case lists 5 failed questions", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
    await testRunner.AndAsync("the case does not reveal the correct answers", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="The verifier approves the case and the node is completed")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Review the verification cases")]
        [global::Xunit.TraitAttribute("Description", "The verifier approves the case and the node is completed")]
        [global::Xunit.TraitAttribute("Category", "US25")]
        public async global::System.Threading.Tasks.Task TheVerifierApprovesTheCaseAndTheNodeIsCompleted()
        {
            string[] tagsOfScenario = new string[] {
                    "US25"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The verifier approves the case and the node is completed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 45
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 46
    await testRunner.GivenAsync("\"ana\" has failed the assessment of the skill \"networking-basics\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 47
    await testRunner.WhenAsync("\"bob\" resolves the case of \"ana\" as \"Approved\" with the notes \"Solid understandin" +
                        "g of the network layers.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 48
    await testRunner.ThenAsync("the response status is 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 49
    await testRunner.AndAsync("the case is resolved as \"Approved\" with the notes \"Solid understanding of the net" +
                        "work layers.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
    await testRunner.AndAsync("the skill \"networking-basics\" of \"ana\" is \"Completed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="The verifier rejects the case and the node stays available")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Review the verification cases")]
        [global::Xunit.TraitAttribute("Description", "The verifier rejects the case and the node stays available")]
        [global::Xunit.TraitAttribute("Category", "US25")]
        public async global::System.Threading.Tasks.Task TheVerifierRejectsTheCaseAndTheNodeStaysAvailable()
        {
            string[] tagsOfScenario = new string[] {
                    "US25"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The verifier rejects the case and the node stays available", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 53
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 54
    await testRunner.GivenAsync("\"ana\" has failed the assessment of the skill \"networking-basics\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 55
    await testRunner.WhenAsync("\"bob\" resolves the case of \"ana\" as \"Rejected\" with the notes \"The explanation of" +
                        " the layers is incomplete.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 56
    await testRunner.ThenAsync("the response status is 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 57
    await testRunner.AndAsync("the case is resolved as \"Rejected\" with the notes \"The explanation of the layers " +
                        "is incomplete.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 58
    await testRunner.AndAsync("the skill \"networking-basics\" of \"ana\" is \"Available\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Only the assigned verifier can resolve the case")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Review the verification cases")]
        [global::Xunit.TraitAttribute("Description", "Only the assigned verifier can resolve the case")]
        [global::Xunit.TraitAttribute("Category", "US25")]
        public async global::System.Threading.Tasks.Task OnlyTheAssignedVerifierCanResolveTheCase()
        {
            string[] tagsOfScenario = new string[] {
                    "US25"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Only the assigned verifier can resolve the case", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 61
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 62
    await testRunner.GivenAsync("\"ana\" has failed the assessment of the skill \"networking-basics\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 63
    await testRunner.WhenAsync("\"carl\" resolves the case of \"ana\" as \"Approved\" with the notes \"Looks fine.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 64
    await testRunner.ThenAsync("the response status is 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 65
    await testRunner.AndAsync("the error is \"NotAssignedVerifier\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Reject a decision without notes")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Review the verification cases")]
        [global::Xunit.TraitAttribute("Description", "Reject a decision without notes")]
        [global::Xunit.TraitAttribute("Category", "US25")]
        public async global::System.Threading.Tasks.Task RejectADecisionWithoutNotes()
        {
            string[] tagsOfScenario = new string[] {
                    "US25"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Reject a decision without notes", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 68
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 69
    await testRunner.GivenAsync("\"ana\" has failed the assessment of the skill \"networking-basics\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 70
    await testRunner.WhenAsync("\"bob\" resolves the case of \"ana\" as \"Approved\" with the notes \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 71
    await testRunner.ThenAsync("the response status is 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 72
    await testRunner.AndAsync("the error is \"RubricNotesRequired\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Reject an unknown decision")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Review the verification cases")]
        [global::Xunit.TraitAttribute("Description", "Reject an unknown decision")]
        [global::Xunit.TraitAttribute("Category", "US25")]
        public async global::System.Threading.Tasks.Task RejectAnUnknownDecision()
        {
            string[] tagsOfScenario = new string[] {
                    "US25"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Reject an unknown decision", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 75
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 76
    await testRunner.GivenAsync("\"ana\" has failed the assessment of the skill \"networking-basics\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 77
    await testRunner.WhenAsync("\"bob\" resolves the case of \"ana\" as \"Maybe\" with the notes \"Not sure.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 78
    await testRunner.ThenAsync("the response status is 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 79
    await testRunner.AndAsync("the error is \"InvalidDecision\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A resolved case cannot be resolved again")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Review the verification cases")]
        [global::Xunit.TraitAttribute("Description", "A resolved case cannot be resolved again")]
        [global::Xunit.TraitAttribute("Category", "US25")]
        public async global::System.Threading.Tasks.Task AResolvedCaseCannotBeResolvedAgain()
        {
            string[] tagsOfScenario = new string[] {
                    "US25"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A resolved case cannot be resolved again", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 82
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 83
    await testRunner.GivenAsync("\"ana\" has failed the assessment of the skill \"networking-basics\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 84
    await testRunner.AndAsync("\"bob\" has resolved the case of \"ana\" as \"Rejected\" with the notes \"Needs more wor" +
                        "k.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 85
    await testRunner.WhenAsync("\"bob\" resolves the case of \"ana\" as \"Approved\" with the notes \"Changed my mind.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 86
    await testRunner.ThenAsync("the response status is 409", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 87
    await testRunner.AndAsync("the error is \"CaseAlreadyResolved\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A student who is not involved cannot consult the case")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Review the verification cases")]
        [global::Xunit.TraitAttribute("Description", "A student who is not involved cannot consult the case")]
        [global::Xunit.TraitAttribute("Category", "US25")]
        public async global::System.Threading.Tasks.Task AStudentWhoIsNotInvolvedCannotConsultTheCase()
        {
            string[] tagsOfScenario = new string[] {
                    "US25"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A student who is not involved cannot consult the case", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 90
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 91
    await testRunner.GivenAsync("\"ana\" has failed the assessment of the skill \"networking-basics\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 92
    await testRunner.WhenAsync("\"carl\" consults the case of \"ana\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 93
    await testRunner.ThenAsync("the response status is 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 94
    await testRunner.AndAsync("the error is \"NotCaseOwner\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="The student attaches evidence to the case")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Review the verification cases")]
        [global::Xunit.TraitAttribute("Description", "The student attaches evidence to the case")]
        [global::Xunit.TraitAttribute("Category", "US26")]
        public async global::System.Threading.Tasks.Task TheStudentAttachesEvidenceToTheCase()
        {
            string[] tagsOfScenario = new string[] {
                    "US26"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The student attaches evidence to the case", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 97
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 98
    await testRunner.GivenAsync("\"ana\" has failed the assessment of the skill \"networking-basics\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 99
    await testRunner.WhenAsync("\"ana\" attaches the evidence \"https://github.com/ana/network-lab\" to the case of \"" +
                        "ana\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 100
    await testRunner.ThenAsync("the response status is 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 101
    await testRunner.AndAsync("the case has the evidence \"https://github.com/ana/network-lab\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Reject evidence that is not a valid link")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Review the verification cases")]
        [global::Xunit.TraitAttribute("Description", "Reject evidence that is not a valid link")]
        [global::Xunit.TraitAttribute("Category", "US26")]
        public async global::System.Threading.Tasks.Task RejectEvidenceThatIsNotAValidLink()
        {
            string[] tagsOfScenario = new string[] {
                    "US26"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Reject evidence that is not a valid link", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 104
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 105
    await testRunner.GivenAsync("\"ana\" has failed the assessment of the skill \"networking-basics\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 106
    await testRunner.WhenAsync("\"ana\" attaches the evidence \"not a link\" to the case of \"ana\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 107
    await testRunner.ThenAsync("the response status is 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 108
    await testRunner.AndAsync("the error is \"InvalidEvidenceUrl\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Only the student can attach evidence to their case")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Review the verification cases")]
        [global::Xunit.TraitAttribute("Description", "Only the student can attach evidence to their case")]
        [global::Xunit.TraitAttribute("Category", "US26")]
        public async global::System.Threading.Tasks.Task OnlyTheStudentCanAttachEvidenceToTheirCase()
        {
            string[] tagsOfScenario = new string[] {
                    "US26"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Only the student can attach evidence to their case", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 111
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 112
    await testRunner.GivenAsync("\"ana\" has failed the assessment of the skill \"networking-basics\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 113
    await testRunner.WhenAsync("\"bob\" attaches the evidence \"https://github.com/bob/work\" to the case of \"ana\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 114
    await testRunner.ThenAsync("the response status is 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 115
    await testRunner.AndAsync("the error is \"NotCaseOwner\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A resolved case does not accept evidence")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Review the verification cases")]
        [global::Xunit.TraitAttribute("Description", "A resolved case does not accept evidence")]
        [global::Xunit.TraitAttribute("Category", "US26")]
        public async global::System.Threading.Tasks.Task AResolvedCaseDoesNotAcceptEvidence()
        {
            string[] tagsOfScenario = new string[] {
                    "US26"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A resolved case does not accept evidence", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 118
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 119
    await testRunner.GivenAsync("\"ana\" has failed the assessment of the skill \"networking-basics\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 120
    await testRunner.AndAsync("\"bob\" has resolved the case of \"ana\" as \"Rejected\" with the notes \"Needs more wor" +
                        "k.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 121
    await testRunner.WhenAsync("\"ana\" attaches the evidence \"https://github.com/ana/network-lab\" to the case of \"" +
                        "ana\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 122
    await testRunner.ThenAsync("the response status is 409", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 123
    await testRunner.AndAsync("the error is \"CaseAlreadyResolved\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ReviewTheVerificationCasesFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ReviewTheVerificationCasesFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
